### ISSUE TITLE
Support for v3.0?

### ISSUE THREAD

**Issue by robertstojs** [brandonmcconnell/tailwind-lerp-colors#1]
Getting the following:

```
warn - As of Tailwind CSS v2.2, `lightBlue` has been renamed to `sky`.
warn - Update your configuration file to silence this warning.

warn - As of Tailwind CSS v3.0, `warmGray` has been renamed to `stone`.
warn - Update your configuration file to silence this warning.

warn - As of Tailwind CSS v3.0, `trueGray` has been renamed to `neutral`.
warn - Update your configuration file to silence this warning.

warn - As of Tailwind CSS v3.0, `coolGray` has been renamed to `gray`.
warn - Update your configuration file to silence this warning.

warn - As of Tailwind CSS v3.0, `blueGray` has been renamed to `slate`.
warn - Update your configuration file to silence this warning.
wait  - compiling...
error - ./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[3].oneOf[8].use[1]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[3].oneOf[8].use[2]!./styles/globals.css
RangeError: Maximum call stack size exceeded
    at Array.map (<anonymous>)
wait  - compiling /_error (client and server)...
wait  - compiling...
error - ./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[3].oneOf[8].use[1]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[3].oneOf[8].use[2]!./styles/globals.css
RangeError: Maximum call stack size exceeded
    at Array.map (<anonymous>)
```

I hope to use this for my projects some day, thanks for starting this

**Comment by brandonmcconnell** [comment]
@robertstojs Thanks for opening this issue! I am currently working to resolve another issue that may be contributing to the error you're seeing, here: https://github.com/tailwindlabs/tailwindcss-intellisense/issues/544

Once that's resolved, I'll also push a change for the color name warnings, so this should be fully compatible soon!

** In the meantime, you should be able to use version `1.1.0` which should resolve that error if it's related to using the `tailwind-lerp-colors` plugin (but not the warnings yet).

**Comment by brandonmcconnell** [comment]
@robertstojs I have reworked my plugin, and v1.1.4 should be stable and ready for use with Tailwind CSS v3.0+. This new version does bring about a paradigm shift in how `tailwind-lerp-colors` is initialized, so be sure to read the [release notes](https://github.com/brandonmcconnell/tailwind-lerp-colors/releases) for versions v1.1.3 and v1.1.4 and the updates top the README ([file](https://github.com/brandonmcconnell/tailwind-lerp-colors/blob/v1.1.4/README.md) / [diff](https://github.com/brandonmcconnell/tailwind-lerp-colors/compare/v1.1.0..v1.1.4)).

I'd be excited to hear if you use this in your own project(s). Thanks again for your interest! 🙌🏼 🌮

**Comment by brandonmcconnell** [comment]
@robertstojs Closing this issue as resolved. If you encounter any further issues, please reach out. I'd love to help make this work for you! 😃
